In [2]:
import numpy as np
import pandas as pd

In [3]:
try: # Running Locally, yakinkan "file_" berada di folder "data"
    df = pd.read_csv("Data Saham Yahoo Finance.csv", low_memory = False, encoding='utf8')
except: # Running in Google Colab
    !mkdir data
    !wget https://raw.githubusercontent.com/dazzerz/-PenerapanRantai-Markov-pada-Data-Saham/main/Data%20Saham%20Yahoo%20Finance.csv
    df = pd.read_csv("Data Saham Yahoo Finance.csv", low_memory = False, encoding='utf8')
df = df[df.columns[1:]]
df


Date  BBCA  EXCL  BBNI  BBRI    BMRI  ASII   GGRM  UNVR  INDF  TLKM
0    12/1/2022  9000  2250  9700  4940  5200.0  6175  18900  4710  6675  3960
1    12/2/2022  8900  2300  9750  4890  5262.5  6125  19425  4710  6775  4000
2    12/5/2022  8775  2300  9750  4890  5437.5  6025  18925  4740  6775  3840
3    12/6/2022  8675  2290  9550  4860  5450.0  5875  18725  4740  6775  3600
4    12/7/2022  8450  2220  9500  4760  5187.5  5725  18850  4700  6850  3680
..         ...   ...   ...   ...   ...     ...   ...    ...   ...   ...   ...
114  5/25/2023  9050  1965  9000  5475  5175.0  6600  27175  4410  7100  4120
115  5/26/2023  9150  1940  8950  5600  5125.0  6600  27575  4380  7200  4130
116  5/29/2023  9150  1945  9050  5550  5150.0  6600  27400  4550  7200  4200
117  5/30/2023  9250  1970  9025  5500  5150.0  6500  27450  4540  7150  4120
118  5/31/2023  9050  1985  9050  5575  5050.0  6450  27000  4530  7100  4040

[119 rows x 11 columns]

In [4]:
labels_BBCA = []
for i in range(1, len(df.BBCA)):
    if df.BBCA[i] > df.BBCA[i-1]:
        labels_BBCA.append("naik")
    elif df.BBCA[i] < df.BBCA[i-1]:
        labels_BBCA.append("turun")
    else:
        labels_BBCA.append("tetap")

labels_EXCL = []
for i in range(1, len(df.EXCL)):
    if df.EXCL[i] > df.EXCL[i-1]:
        labels_EXCL.append("naik")
    elif df.EXCL[i] < df.EXCL[i-1]:
        labels_EXCL.append("turun")
    else:
        labels_EXCL.append("tetap")

labels_BBNI	 = []
for i in range(1, len(df.BBNI)):
    if df.BBNI[i] > df.BBNI[i-1]:
        labels_BBNI.append("naik")
    elif df.BBNI[i] < df.BBNI[i-1]:
        labels_BBNI.append("turun")
    else:
        labels_BBNI.append("tetap")

labels_BBRI	 = []
for i in range(1, len(df.BBRI)):
    if df.BBRI[i] > df.BBRI[i-1]:
        labels_BBRI.append("naik")
    elif df.BBRI[i] < df.BBRI[i-1]:
        labels_BBRI.append("turun")
    else:
        labels_BBRI.append("tetap")

labels_BMRI	 = []
for i in range(1, len(df.BMRI)):
    if df.BMRI[i] > df.BMRI[i-1]:
        labels_BMRI.append("naik")
    elif df.BMRI[i] < df.BMRI[i-1]:
        labels_BMRI.append("turun")
    else:
        labels_BMRI.append("tetap")

labels_ASII = []
for i in range(1, len(df.ASII)):
    if df.ASII[i] > df.ASII[i-1]:
        labels_ASII.append("naik")
    elif df.ASII[i] < df.ASII[i-1]:
        labels_ASII.append("turun")
    else:
        labels_ASII.append("tetap")

labels_UNVR	 = []
for i in range(1, len(df.UNVR)):
    if df.UNVR[i] > df.UNVR[i-1]:
        labels_UNVR.append("naik")
    elif df.UNVR[i] < df.UNVR[i-1]:
        labels_UNVR.append("turun")
    else:
        labels_UNVR.append("tetap")

labels_GGRM	 = []
for i in range(1, len(df.GGRM)):
    if df.GGRM[i] > df.GGRM[i-1]:
        labels_GGRM.append("naik")
    elif df.GGRM[i] < df.GGRM[i-1]:
        labels_GGRM.append("turun")
    else:
        labels_GGRM.append("tetap")

labels_INDF	 = []
for i in range(1, len(df.INDF)):
    if df.INDF[i] > df.INDF[i-1]:
        labels_INDF.append("naik")
    elif df.INDF[i] < df.INDF[i-1]:
        labels_INDF.append("turun")
    else:
        labels_INDF.append("tetap")

labels_TLKM	 = []
for i in range(1, len(df.TLKM)):
    if df.TLKM[i] > df.TLKM[i-1]:
        labels_TLKM.append("naik")
    elif df.TLKM[i] < df.TLKM[i-1]:
        labels_TLKM.append("turun")
    else:
        labels_TLKM.append("tetap")

print(len(labels_BBCA))
print(len(labels_EXCL))
print(len(labels_BBNI))
print(len(labels_BBRI))
print(len(labels_BMRI))
print(len(labels_ASII))
print(len(labels_UNVR))        
print(len(labels_GGRM))
print(len(labels_INDF))
print(len(labels_TLKM))

118
118
118
118
118
118
118
118
118
118


In [5]:
data = {
    'BBCA': labels_BBCA,
    'EXCL': labels_EXCL,
    'BBNI': labels_BBNI,
    'BBRI': labels_BBRI,
    'BMRI': labels_BMRI,
    'ASII': labels_ASII,
    'UNVR': labels_UNVR,
    'GGRM': labels_GGRM,
    'INDF': labels_INDF,
    'TLKM': labels_TLKM
}

Data_perubahan = pd.DataFrame(data)
Data_perubahan

BBCA   EXCL   BBNI   BBRI   BMRI   ASII   UNVR   GGRM   INDF   TLKM
0    turun   naik   naik  turun   naik  turun  tetap   naik   naik   naik
1    turun  tetap  tetap  tetap   naik  turun   naik  turun  tetap  turun
2    turun  turun  turun  turun   naik  turun  tetap  turun  tetap  turun
3    turun  turun  turun  turun  turun  turun  turun   naik   naik   naik
4     naik  turun  tetap   naik  turun  turun  turun   naik   naik   naik
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
113   naik   naik   naik  turun   naik  turun  tetap  turun   naik  turun
114   naik  turun  turun   naik  turun  tetap  turun   naik   naik   naik
115  tetap   naik   naik  turun   naik  tetap   naik  turun  tetap   naik
116   naik   naik  turun  turun  tetap  turun  turun   naik  turun  turun
117  turun   naik   naik   naik  turun  turun  turun  turun  turun  turun

[118 rows x 10 columns]

In [7]:
# Membuat matriks peluang transisi BBCA
states = ['turun', 'naik', 'tetap']
jumlah_state = len(states)
frek_matriks_transisi = np.zeros((jumlah_state, jumlah_state))

for i in range(len(Data_perubahan['BBCA']) - 1):
    current_state = Data_perubahan['BBCA'][i]
    next_state = Data_perubahan['BBCA'][i + 1]
    current_index = states.index(current_state)
    next_index = states.index(next_state)
    frek_matriks_transisi[current_index][next_index] += 1

# Menghitung jumlah frekuensi peralihan state
frekuensi_peralihan_BBCA = np.sum(frek_matriks_transisi, axis=1)

# Normalisasi matriks transisi menjadi peluang transisi
matriks_transisi_BBCA = frek_matriks_transisi / frekuensi_peralihan_BBCA[:, np.newaxis]

# Menampilkan matriks peluang transisi
print("Frekuensi Matriks Peluang Transisi:")
print(frek_matriks_transisi)
print("Jumlah barisan matriks BBCA:")
print(frekuensi_peralihan_BBCA)
print("Matriks Transisi BBCA:")
print(matriks_transisi_BBCA)

Frekuensi Matriks Peluang Transisi:
[[20. 26.  4.]
 [22. 27.  6.]
 [ 8.  2.  2.]]
Jumlah barisan matriks BBCA:
[50. 55. 12.]
Matriks Transisi BBCA:
[[0.4        0.52       0.08      ]
 [0.4        0.49090909 0.10909091]
 [0.66666667 0.16666667 0.16666667]]


In [8]:
# Membuat matriks peluang transisi EXCL
states = ['turun', 'naik', 'tetap']
jumlah_state = len(states)
frek_matriks_transisi = np.zeros((jumlah_state, jumlah_state))

for i in range(len(Data_perubahan['EXCL']) - 1):
    current_state = Data_perubahan['EXCL'][i]
    next_state = Data_perubahan['EXCL'][i + 1]
    current_index = states.index(current_state)
    next_index = states.index(next_state)
    frek_matriks_transisi[current_index][next_index] += 1

# Menghitung jumlah frekuensi peralihan state
frekuensi_peralihan_EXCL = np.sum(frek_matriks_transisi, axis=1)

# Normalisasi matriks transisi menjadi peluang transisi
matriks_transisi_EXCL = frek_matriks_transisi / frekuensi_peralihan_EXCL[:, np.newaxis]

# Menampilkan matriks peluang transisi
print("Frekuensi Matriks Peluang Transisi:")
print(frek_matriks_transisi)
print("Jumlah barisan matriks EXCL:")
print(frekuensi_peralihan_EXCL)
print("Matriks Transisi EXCL:")
print(matriks_transisi_EXCL)

Frekuensi Matriks Peluang Transisi:
[[28. 27.  5.]
 [26. 19.  3.]
 [ 6.  2.  1.]]
Jumlah barisan matriks EXCL:
[60. 48.  9.]
Matriks Transisi EXCL:
[[0.46666667 0.45       0.08333333]
 [0.54166667 0.39583333 0.0625    ]
 [0.66666667 0.22222222 0.11111111]]


In [10]:
# Membuat matriks peluang transisi BBNI
states = ['turun', 'naik', 'tetap']
jumlah_state = len(states)
frek_matriks_transisi = np.zeros((jumlah_state, jumlah_state))

for i in range(len(Data_perubahan['BBNI']) - 1):
    current_state = Data_perubahan['BBNI'][i]
    next_state = Data_perubahan['BBNI'][i + 1]
    current_index = states.index(current_state)
    next_index = states.index(next_state)
    frek_matriks_transisi[current_index][next_index] += 1

# Menghitung jumlah frekuensi peralihan state
frekuensi_peralihan_BBNI = np.sum(frek_matriks_transisi, axis=1)

# Normalisasi matriks transisi menjadi peluang transisi
matriks_transisi_BBNI = frek_matriks_transisi / frekuensi_peralihan_BBNI[:, np.newaxis]

# Menampilkan matriks peluang transisi
print("Frekuensi Matriks Peluang Transisi:")
print(frek_matriks_transisi)
print("Jumlah barisan matriks BBNI:")
print(frekuensi_peralihan_BBNI)
print("Matriks Transisi BBNI:")
print(matriks_transisi_BBNI)

Frekuensi Matriks Peluang Transisi:
[[29. 24.  4.]
 [25. 23.  2.]
 [ 3.  3.  4.]]
Jumlah barisan matriks BBNI:
[57. 50. 10.]
Matriks Transisi BBNI:
[[0.50877193 0.42105263 0.07017544]
 [0.5        0.46       0.04      ]
 [0.3        0.3        0.4       ]]


In [11]:
# Membuat matriks peluang transisi BBRI
states = ['turun', 'naik', 'tetap']
jumlah_state = len(states)
frek_matriks_transisi = np.zeros((jumlah_state, jumlah_state))

for i in range(len(Data_perubahan['BBRI']) - 1):
    current_state = Data_perubahan['BBRI'][i]
    next_state = Data_perubahan['BBRI'][i + 1]
    current_index = states.index(current_state)
    next_index = states.index(next_state)
    frek_matriks_transisi[current_index][next_index] += 1

# Menghitung jumlah frekuensi peralihan state
frekuensi_peralihan_BBRI = np.sum(frek_matriks_transisi, axis=1)

# Normalisasi matriks transisi menjadi peluang transisi
matriks_transisi_BBRI = frek_matriks_transisi / frekuensi_peralihan_BBRI[:, np.newaxis]

# Menampilkan matriks peluang transisi
print("Frekuensi Matriks Peluang Transisi:")
print(frek_matriks_transisi)
print("Jumlah barisan matriks BBRI:")
print(frekuensi_peralihan_BBRI)
print("Matriks Transisi BBRI:")
print(matriks_transisi_BBRI)

Frekuensi Matriks Peluang Transisi:
[[19. 28.  1.]
 [25. 30.  5.]
 [ 3.  3.  3.]]
Jumlah barisan matriks BBRI:
[48. 60.  9.]
Matriks Transisi BBRI:
[[0.39583333 0.58333333 0.02083333]
 [0.41666667 0.5        0.08333333]
 [0.33333333 0.33333333 0.33333333]]


In [12]:
# Membuat matriks peluang transisi BMRI
states = ['turun', 'naik', 'tetap']
jumlah_state = len(states)
frek_matriks_transisi = np.zeros((jumlah_state, jumlah_state))

for i in range(len(Data_perubahan['BMRI']) - 1):
    current_state = Data_perubahan['BMRI'][i]
    next_state = Data_perubahan['BMRI'][i + 1]
    current_index = states.index(current_state)
    next_index = states.index(next_state)
    frek_matriks_transisi[current_index][next_index] += 1

# Menghitung jumlah frekuensi peralihan state
frekuensi_peralihan_BMRI = np.sum(frek_matriks_transisi, axis=1)

# Normalisasi matriks transisi menjadi peluang transisi
matriks_transisi_BMRI = frek_matriks_transisi / frekuensi_peralihan_BMRI[:, np.newaxis]

# Menampilkan matriks peluang transisi
print("Frekuensi Matriks Peluang Transisi:")
print(frek_matriks_transisi)
print("Jumlah barisan matriks BMRI:")
print(frekuensi_peralihan_BMRI)
print("Matriks Transisi BMRI:")
print(matriks_transisi_BMRI)

Frekuensi Matriks Peluang Transisi:
[[20. 31.  3.]
 [30. 24.  3.]
 [ 5.  1.  0.]]
Jumlah barisan matriks BMRI:
[54. 57.  6.]
Matriks Transisi BMRI:
[[0.37037037 0.57407407 0.05555556]
 [0.52631579 0.42105263 0.05263158]
 [0.83333333 0.16666667 0.        ]]


In [13]:
# Membuat matriks peluang transisi ASII
states = ['turun', 'naik', 'tetap']
jumlah_state = len(states)
frek_matriks_transisi = np.zeros((jumlah_state, jumlah_state))

for i in range(len(Data_perubahan['ASII']) - 1):
    current_state = Data_perubahan['ASII'][i]
    next_state = Data_perubahan['ASII'][i + 1]
    current_index = states.index(current_state)
    next_index = states.index(next_state)
    frek_matriks_transisi[current_index][next_index] += 1

# Menghitung jumlah frekuensi peralihan state
frekuensi_peralihan_ASII = np.sum(frek_matriks_transisi, axis=1)

# Normalisasi matriks transisi menjadi peluang transisi
matriks_transisi_ASII = frek_matriks_transisi / frekuensi_peralihan_ASII[:, np.newaxis]

# Menampilkan matriks peluang transisi
print("Frekuensi Matriks Peluang Transisi:")
print(frek_matriks_transisi)
print("Jumlah barisan matriks:")
print(frekuensi_peralihan_ASII)
print("Matriks Transisi ASII:")
print(matriks_transisi_ASII)

Frekuensi Matriks Peluang Transisi:
[[26. 19.  5.]
 [16. 19. 12.]
 [ 8.  9.  3.]]
Jumlah barisan matriks:
[50. 47. 20.]
Matriks Transisi ASII:
[[0.52       0.38       0.1       ]
 [0.34042553 0.40425532 0.25531915]
 [0.4        0.45       0.15      ]]


In [14]:
# Membuat matriks peluang transisi UNVR
states = ['turun', 'naik', 'tetap']
jumlah_state = len(states)
frek_matriks_transisi = np.zeros((jumlah_state, jumlah_state))

for i in range(len(Data_perubahan['UNVR']) - 1):
    current_state = Data_perubahan['UNVR'][i]
    next_state = Data_perubahan['UNVR'][i + 1]
    current_index = states.index(current_state)
    next_index = states.index(next_state)
    frek_matriks_transisi[current_index][next_index] += 1

# Menghitung jumlah frekuensi peralihan state
frekuensi_peralihan_UNVR = np.sum(frek_matriks_transisi, axis=1)

# Normalisasi matriks transisi menjadi peluang transisi
matriks_transisi_UNVR = frek_matriks_transisi / frekuensi_peralihan_UNVR[:, np.newaxis]

# Menampilkan matriks peluang transisi
print("Frekuensi Matriks Peluang Transisi:")
print(frek_matriks_transisi)
print("Jumlah barisan matriks UNVR:")
print(frekuensi_peralihan_UNVR)
print("Matriks Transisi UNVR:")
print(matriks_transisi_UNVR)

Frekuensi Matriks Peluang Transisi:
[[29. 22.  4.]
 [21. 20.  7.]
 [ 6.  6.  2.]]
Jumlah barisan matriks UNVR:
[55. 48. 14.]
Matriks Transisi UNVR:
[[0.52727273 0.4        0.07272727]
 [0.4375     0.41666667 0.14583333]
 [0.42857143 0.42857143 0.14285714]]


In [15]:
# Membuat matriks peluang transisi GGRM
states = ['turun', 'naik', 'tetap']
jumlah_state = len(states)
frek_matriks_transisi = np.zeros((jumlah_state, jumlah_state))

for i in range(len(Data_perubahan['GGRM']) - 1):
    current_state = Data_perubahan['GGRM'][i]
    next_state = Data_perubahan['GGRM'][i + 1]
    current_index = states.index(current_state)
    next_index = states.index(next_state)
    frek_matriks_transisi[current_index][next_index] += 1

# Menghitung jumlah frekuensi peralihan state
frekuensi_peralihan_GGRM = np.sum(frek_matriks_transisi, axis=1)

# Normalisasi matriks transisi menjadi peluang transisi
matriks_transisi_GGRM = frek_matriks_transisi / frekuensi_peralihan_GGRM[:, np.newaxis]

# Menampilkan matriks peluang transisi
print("Frekuensi Matriks Peluang Transisi:")
print(frek_matriks_transisi)
print("Jumlah barisan matriks GGRM:")
print(frekuensi_peralihan_GGRM)
print("Matriks Transisi GGRM:")
print(matriks_transisi_GGRM)

Frekuensi Matriks Peluang Transisi:
[[26. 33.  0.]
 [34. 22.  1.]
 [ 0.  1.  0.]]
Jumlah barisan matriks GGRM:
[59. 57.  1.]
Matriks Transisi GGRM:
[[0.44067797 0.55932203 0.        ]
 [0.59649123 0.38596491 0.01754386]
 [0.         1.         0.        ]]


In [16]:
# Membuat matriks peluang transisi INDF
states = ['turun', 'naik', 'tetap']
jumlah_state = len(states)
frek_matriks_transisi = np.zeros((jumlah_state, jumlah_state))

for i in range(len(Data_perubahan['INDF']) - 1):
    current_state = Data_perubahan['INDF'][i]
    next_state = Data_perubahan['INDF'][i + 1]
    current_index = states.index(current_state)
    next_index = states.index(next_state)
    frek_matriks_transisi[current_index][next_index] += 1

# Menghitung jumlah frekuensi peralihan state
frekuensi_peralihan_INDF = np.sum(frek_matriks_transisi, axis=1)

# Normalisasi matriks transisi menjadi peluang transisi
matriks_transisi_INDF = frek_matriks_transisi / frekuensi_peralihan_INDF[:, np.newaxis]

# Menampilkan matriks peluang transisi
print("Frekuensi Matriks Peluang Transisi:")
print(frek_matriks_transisi)
print("Jumlah barisan matriks INDF:")
print(frekuensi_peralihan_INDF)
print("Matriks Transisi INDF:")
print(matriks_transisi_INDF)

Frekuensi Matriks Peluang Transisi:
[[13. 23. 11.]
 [29. 15.  7.]
 [ 6. 12.  1.]]
Jumlah barisan matriks INDF:
[47. 51. 19.]
Matriks Transisi INDF:
[[0.27659574 0.4893617  0.23404255]
 [0.56862745 0.29411765 0.1372549 ]
 [0.31578947 0.63157895 0.05263158]]


In [17]:
# Membuat matriks peluang transisi TLKM
states = ['turun', 'naik', 'tetap']
jumlah_state = len(states)
frek_matriks_transisi = np.zeros((jumlah_state, jumlah_state))

for i in range(len(Data_perubahan['TLKM']) - 1):
    current_state = Data_perubahan['TLKM'][i]
    next_state = Data_perubahan['TLKM'][i + 1]
    current_index = states.index(current_state)
    next_index = states.index(next_state)
    frek_matriks_transisi[current_index][next_index] += 1

# Menghitung jumlah frekuensi peralihan state
frekuensi_peralihan_TLKM = np.sum(frek_matriks_transisi, axis=1)

# Normalisasi matriks transisi menjadi peluang transisi
matriks_transisi_TLKM = frek_matriks_transisi / frekuensi_peralihan_TLKM[:, np.newaxis]

# Menampilkan matriks peluang transisi
print("Frekuensi Matriks Peluang Transisi:")
print(frek_matriks_transisi)
print("Jumlah barisan matriks TLKM:")
print(frekuensi_peralihan_TLKM)
print("Matriks Transisi TLKM:")
print(matriks_transisi_TLKM)

Frekuensi Matriks Peluang Transisi:
[[19. 23.  7.]
 [26. 22.  6.]
 [ 5.  8.  1.]]
Jumlah barisan matriks TLKM:
[49. 54. 14.]
Matriks Transisi TLKM:
[[0.3877551  0.46938776 0.14285714]
 [0.48148148 0.40740741 0.11111111]
 [0.35714286 0.57142857 0.07142857]]


In [115]:
# Matriks peluang transisi satu langkah
matriks_transisi_satu_langkah_BBCA = matriks_transisi_BBCA

# Fungsi untuk menghitung matriks peluang transisi n langkah
def hitung_matriks_peluang_transisi(langkah, matriks_satu_langkah):
    matriks_peluang_transisi = np.linalg.matrix_power(matriks_satu_langkah, langkah)
    return matriks_peluang_transisi

# Menghitung matriks peluang transisi 2 langkah
matriks_peluang_transisi_2_BBCA = hitung_matriks_peluang_transisi(2, matriks_transisi_satu_langkah_BBCA)

# Menghitung matriks peluang transisi 3 langkah
matriks_peluang_transisi_3_BBCA = hitung_matriks_peluang_transisi(3, matriks_transisi_satu_langkah_BBCA)

# Menghitung matriks peluang transisi 4 langkah
matriks_peluang_transisi_4_BBCA = hitung_matriks_peluang_transisi(4, matriks_transisi_satu_langkah_BBCA)

# Menampilkan hasil perkalian matriks peluang transisi
print("Matriks Peluang Transisi 2 langkah:")
print(matriks_peluang_transisi_2_BBCA)
print()

print("Matriks Peluang Transisi 3 langkah:")
print(matriks_peluang_transisi_3_BBCA)
print()

print("Matriks Peluang Transisi 4 langkah:")
print(matriks_peluang_transisi_4_BBCA)

Matriks Peluang Transisi 2 langkah:
[[0.42133333 0.47660606 0.10206061]
 [0.42909091 0.46717355 0.10373554]
 [0.44444444 0.45626263 0.09929293]]

Matriks Peluang Transisi 3 langkah:
[[0.42721616 0.47007368 0.10271016]
 [0.42766281 0.46975627 0.10258092]
 [0.42647811 0.4716434  0.10187848]]

Matriks Peluang Transisi 4 langkah:
[[0.42738937 0.47003421 0.10257642]
 [0.42735491 0.47008911 0.10255598]
 [0.4271676  0.4702824  0.10255   ]]


In [117]:
# Matriks peluang transisi satu langkah
matriks_transisi_satu_langkah = matriks_transisi_EXCL

# Fungsi untuk menghitung matriks peluang transisi n langkah
def hitung_matriks_peluang_transisi(langkah, matriks_satu_langkah):
    matriks_peluang_transisi = np.linalg.matrix_power(matriks_satu_langkah, langkah)
    return matriks_peluang_transisi

# Menghitung matriks peluang transisi 2 langkah
matriks_peluang_transisi_2 = hitung_matriks_peluang_transisi(2, matriks_transisi_satu_langkah)

# Menghitung matriks peluang transisi 3 langkah
matriks_peluang_transisi_3 = hitung_matriks_peluang_transisi(3, matriks_transisi_satu_langkah)

# Menghitung matriks peluang transisi 4 langkah
matriks_peluang_transisi_4 = hitung_matriks_peluang_transisi(4, matriks_transisi_satu_langkah)

# Menampilkan hasil perkalian matriks peluang transisi
print("Matriks Peluang Transisi 2 langkah:")
print(matriks_peluang_transisi_2)
print()

print("Matriks Peluang Transisi 3 langkah:")
print(matriks_peluang_transisi_3)
print()

print("Matriks Peluang Transisi 4 langkah:")
print(matriks_peluang_transisi_4)

Matriks Peluang Transisi 2 langkah:
[[0.51708333 0.40664352 0.07627315]
 [0.50885417 0.41432292 0.07682292]
 [0.50555556 0.41265432 0.08179012]]

Matriks Peluang Transisi 3 langkah:
[[0.51241956 0.41060015 0.07698029]
 [0.51310547 0.41005896 0.07683558]
 [0.51397377 0.40901792 0.07700832]]

Matriks Peluang Transisi 4 langkah:
[[0.51285774 0.41022476 0.07691751]
 [0.5127882  0.41028704 0.07692476]
 [0.51274467 0.41030408 0.07695125]]


In [118]:
# Matriks peluang transisi satu langkah
matriks_transisi_satu_langkah = matriks_transisi_BBNI

# Fungsi untuk menghitung matriks peluang transisi n langkah
def hitung_matriks_peluang_transisi(langkah, matriks_satu_langkah):
    matriks_peluang_transisi = np.linalg.matrix_power(matriks_satu_langkah, langkah)
    return matriks_peluang_transisi

# Menghitung matriks peluang transisi 2 langkah
matriks_peluang_transisi_2 = hitung_matriks_peluang_transisi(2, matriks_transisi_satu_langkah)

# Menghitung matriks peluang transisi 3 langkah
matriks_peluang_transisi_3 = hitung_matriks_peluang_transisi(3, matriks_transisi_satu_langkah)

# Menghitung matriks peluang transisi 4 langkah
matriks_peluang_transisi_4 = hitung_matriks_peluang_transisi(4, matriks_transisi_satu_langkah)

# Menampilkan hasil perkalian matriks peluang transisi
print("Matriks Peluang Transisi 2 langkah:")
print(matriks_peluang_transisi_2)
print()

print("Matriks Peluang Transisi 3 langkah:")
print(matriks_peluang_transisi_3)
print()

print("Matriks Peluang Transisi 4 langkah:")
print(matriks_peluang_transisi_4)

Matriks Peluang Transisi 2 langkah:
[[0.49042782 0.4289566  0.08061557]
 [0.49638596 0.43412632 0.06948772]
 [0.42263158 0.38431579 0.19305263]]

Matriks Peluang Transisi 3 langkah:
[[0.48817888 0.42800064 0.08382048]
 [0.49045672 0.42954904 0.07999424]
 [0.46509677 0.41265119 0.12225204]]

Matriks Peluang Transisi 4 langkah:
[[0.48751817 0.42757544 0.08490639]
 [0.4883034  0.42809892 0.08359767]
 [0.47962939 0.42232538 0.09804523]]


In [119]:
# Matriks peluang transisi satu langkah
matriks_transisi_satu_langkah = matriks_transisi_BBRI

# Fungsi untuk menghitung matriks peluang transisi n langkah
def hitung_matriks_peluang_transisi(langkah, matriks_satu_langkah):
    matriks_peluang_transisi = np.linalg.matrix_power(matriks_satu_langkah, langkah)
    return matriks_peluang_transisi

# Menghitung matriks peluang transisi 2 langkah
matriks_peluang_transisi_2 = hitung_matriks_peluang_transisi(2, matriks_transisi_satu_langkah)

# Menghitung matriks peluang transisi 3 langkah
matriks_peluang_transisi_3 = hitung_matriks_peluang_transisi(3, matriks_transisi_satu_langkah)

# Menghitung matriks peluang transisi 4 langkah
matriks_peluang_transisi_4 = hitung_matriks_peluang_transisi(4, matriks_transisi_satu_langkah)

# Menampilkan hasil perkalian matriks peluang transisi
print("Matriks Peluang Transisi 2 langkah:")
print(matriks_peluang_transisi_2)
print()

print("Matriks Peluang Transisi 3 langkah:")
print(matriks_peluang_transisi_3)
print()

print("Matriks Peluang Transisi 4 langkah:")
print(matriks_peluang_transisi_4)

Matriks Peluang Transisi 2 langkah:
[[0.40668403 0.52951389 0.06380208]
 [0.40104167 0.52083333 0.078125  ]
 [0.38194444 0.47222222 0.14583333]]

Matriks Peluang Transisi 3 langkah:
[[0.40287724 0.52325666 0.0738661 ]
 [0.40180122 0.52039931 0.07779948]
 [0.39655671 0.50752315 0.09592014]]

Matriks Peluang Transisi 4 langkah:
[[0.40211788 0.52126209 0.07662003]
 [0.40181252 0.52051685 0.07767063]
 [0.40041172 0.5170597  0.08252857]]


In [120]:
# Matriks peluang transisi satu langkah
matriks_transisi_satu_langkah = matriks_transisi_BMRI

# Fungsi untuk menghitung matriks peluang transisi n langkah
def hitung_matriks_peluang_transisi(langkah, matriks_satu_langkah):
    matriks_peluang_transisi = np.linalg.matrix_power(matriks_satu_langkah, langkah)
    return matriks_peluang_transisi

# Menghitung matriks peluang transisi 2 langkah
matriks_peluang_transisi_2 = hitung_matriks_peluang_transisi(2, matriks_transisi_satu_langkah)

# Menghitung matriks peluang transisi 3 langkah
matriks_peluang_transisi_3 = hitung_matriks_peluang_transisi(3, matriks_transisi_satu_langkah)

# Menghitung matriks peluang transisi 4 langkah
matriks_peluang_transisi_4 = hitung_matriks_peluang_transisi(4, matriks_transisi_satu_langkah)

# Menampilkan hasil perkalian matriks peluang transisi
print("Matriks Peluang Transisi 2 langkah:")
print(matriks_peluang_transisi_2)
print()

print("Matriks Peluang Transisi 3 langkah:")
print(matriks_peluang_transisi_3)
print()

print("Matriks Peluang Transisi 4 langkah:")
print(matriks_peluang_transisi_4)

Matriks Peluang Transisi 2 langkah:
[[0.48561476 0.46359469 0.05079056]
 [0.46039807 0.4882015  0.05140043]
 [0.39636127 0.5485705  0.05506823]]

Matriks Peluang Transisi 3 langkah:
[[0.46617998 0.4824417  0.05137832]
 [0.47029965 0.47842786 0.05127249]
 [0.48141198 0.46769582 0.0508922 ]]

Matriks Peluang Transisi 4 langkah:
[[0.4693912  0.47931824 0.05129056]
 [0.46871627 0.47997556 0.05130817]
 [0.4668666  0.48177272 0.05136068]]


In [121]:
# Matriks peluang transisi satu langkah
matriks_transisi_satu_langkah = matriks_transisi_ASII

# Fungsi untuk menghitung matriks peluang transisi n langkah
def hitung_matriks_peluang_transisi(langkah, matriks_satu_langkah):
    matriks_peluang_transisi = np.linalg.matrix_power(matriks_satu_langkah, langkah)
    return matriks_peluang_transisi

# Menghitung matriks peluang transisi 2 langkah
matriks_peluang_transisi_2 = hitung_matriks_peluang_transisi(2, matriks_transisi_satu_langkah)

# Menghitung matriks peluang transisi 3 langkah
matriks_peluang_transisi_3 = hitung_matriks_peluang_transisi(3, matriks_transisi_satu_langkah)

# Menghitung matriks peluang transisi 4 langkah
matriks_peluang_transisi_4 = hitung_matriks_peluang_transisi(4, matriks_transisi_satu_langkah)

# Menampilkan hasil perkalian matriks peluang transisi
print("Matriks Peluang Transisi 2 langkah:")
print(matriks_peluang_transisi_2)
print()

print("Matriks Peluang Transisi 3 langkah:")
print(matriks_peluang_transisi_3)
print()

print("Matriks Peluang Transisi 4 langkah:")
print(matriks_peluang_transisi_4)

Matriks Peluang Transisi 2 langkah:
[[0.4397617  0.39621702 0.16402128]
 [0.41676777 0.40767768 0.17555455]
 [0.42119149 0.40141489 0.17739362]]

Matriks Peluang Transisi 3 langkah:
[[0.42916699 0.40109186 0.16974115]
 [0.42572495 0.40217717 0.17209788]
 [0.4266289  0.402154   0.1712171 ]]

Matriks Peluang Transisi 4 langkah:
[[0.4276052  0.40161049 0.1707843 ]
 [0.4271275  0.40180179 0.17107071]
 [0.42723736 0.40173957 0.17102307]]


In [122]:
# Matriks peluang transisi satu langkah
matriks_transisi_satu_langkah = matriks_transisi_UNVR

# Fungsi untuk menghitung matriks peluang transisi n langkah
def hitung_matriks_peluang_transisi(langkah, matriks_satu_langkah):
    matriks_peluang_transisi = np.linalg.matrix_power(matriks_satu_langkah, langkah)
    return matriks_peluang_transisi

# Menghitung matriks peluang transisi 2 langkah
matriks_peluang_transisi_2 = hitung_matriks_peluang_transisi(2, matriks_transisi_satu_langkah)

# Menghitung matriks peluang transisi 3 langkah
matriks_peluang_transisi_3 = hitung_matriks_peluang_transisi(3, matriks_transisi_satu_langkah)

# Menghitung matriks peluang transisi 4 langkah
matriks_peluang_transisi_4 = hitung_matriks_peluang_transisi(4, matriks_transisi_satu_langkah)

# Menampilkan hasil perkalian matriks peluang transisi
print("Matriks Peluang Transisi 2 langkah:")
print(matriks_peluang_transisi_2)
print()

print("Matriks Peluang Transisi 3 langkah:")
print(matriks_peluang_transisi_3)
print()

print("Matriks Peluang Transisi 4 langkah:")
print(matriks_peluang_transisi_4)

Matriks Peluang Transisi 2 langkah:
[[0.48418536 0.40874459 0.10707005]
 [0.47547348 0.41111111 0.1134154 ]
 [0.47469852 0.41122449 0.11407699]]

Matriks Peluang Transisi 3 langkah:
[[0.48001066 0.40987155 0.11011779]
 [0.47917191 0.41009229 0.11073579]
 [0.47909644 0.41011308 0.11079048]]

Matriks Peluang Transisi 4 langkah:
[[0.47960867 0.40997742 0.11041391]
 [0.47952786 0.40999875 0.11047339]
 [0.47952059 0.41000066 0.11047875]]


In [123]:
# Matriks peluang transisi satu langkah
matriks_transisi_satu_langkah = matriks_transisi_GGRM

# Fungsi untuk menghitung matriks peluang transisi n langkah
def hitung_matriks_peluang_transisi(langkah, matriks_satu_langkah):
    matriks_peluang_transisi = np.linalg.matrix_power(matriks_satu_langkah, langkah)
    return matriks_peluang_transisi

# Menghitung matriks peluang transisi 2 langkah
matriks_peluang_transisi_2 = hitung_matriks_peluang_transisi(2, matriks_transisi_satu_langkah)

# Menghitung matriks peluang transisi 3 langkah
matriks_peluang_transisi_3 = hitung_matriks_peluang_transisi(3, matriks_transisi_satu_langkah)

# Menghitung matriks peluang transisi 4 langkah
matriks_peluang_transisi_4 = hitung_matriks_peluang_transisi(4, matriks_transisi_satu_langkah)

# Menampilkan hasil perkalian matriks peluang transisi
print("Matriks Peluang Transisi 2 langkah:")
print(matriks_peluang_transisi_2)
print()

print("Matriks Peluang Transisi 3 langkah:")
print(matriks_peluang_transisi_3)
print()

print("Matriks Peluang Transisi 4 langkah:")
print(matriks_peluang_transisi_4)

Matriks Peluang Transisi 2 langkah:
[[0.52782776 0.46235958 0.00981267]
 [0.49308523 0.50014346 0.00677131]
 [0.59649123 0.38596491 0.01754386]]

Matriks Peluang Transisi 3 langkah:
[[0.50839549 0.48349293 0.00811157]
 [0.51562298 0.47560257 0.00877445]
 [0.49308523 0.50014346 0.00677131]]

Matriks Peluang Transisi 4 langkah:
[[0.51243799 0.47907968 0.00848233]
 [0.51091645 0.48073965 0.0083439 ]
 [0.51562298 0.47560257 0.00877445]]


In [124]:
# Matriks peluang transisi satu langkah
matriks_transisi_satu_langkah = matriks_transisi_INDF

# Fungsi untuk menghitung matriks peluang transisi n langkah
def hitung_matriks_peluang_transisi(langkah, matriks_satu_langkah):
    matriks_peluang_transisi = np.linalg.matrix_power(matriks_satu_langkah, langkah)
    return matriks_peluang_transisi

# Menghitung matriks peluang transisi 2 langkah
matriks_peluang_transisi_2 = hitung_matriks_peluang_transisi(2, matriks_transisi_satu_langkah)

# Menghitung matriks peluang transisi 3 langkah
matriks_peluang_transisi_3 = hitung_matriks_peluang_transisi(3, matriks_transisi_satu_langkah)

# Menghitung matriks peluang transisi 4 langkah
matriks_peluang_transisi_4 = hitung_matriks_peluang_transisi(4, matriks_transisi_satu_langkah)

# Menampilkan hasil perkalian matriks peluang transisi
print("Matriks Peluang Transisi 2 langkah:")
print(matriks_peluang_transisi_2)
print()

print("Matriks Peluang Transisi 3 langkah:")
print(matriks_peluang_transisi_3)
print()

print("Matriks Peluang Transisi 4 langkah:")
print(matriks_peluang_transisi_4)

Matriks Peluang Transisi 2 langkah:
[[0.42867788 0.42710163 0.1442205 ]
 [0.36786695 0.45145699 0.18067605]
 [0.46309965 0.37353479 0.16336556]]

Matriks Peluang Transisi 3 langkah:
[[0.4069755  0.42648329 0.16654121]
 [0.41551687 0.42691266 0.15757047]
 [0.39208265 0.43966466 0.16825269]]

Matriks Peluang Transisi 4 langkah:
[[0.40766976 0.42977841 0.16255183]
 [0.40744355 0.42841878 0.16413767]
 [0.41158621 0.42744823 0.16096556]]


In [125]:
# Matriks peluang transisi satu langkah
matriks_transisi_satu_langkah = matriks_transisi_TLKM

# Fungsi untuk menghitung matriks peluang transisi n langkah
def hitung_matriks_peluang_transisi(langkah, matriks_satu_langkah):
    matriks_peluang_transisi = np.linalg.matrix_power(matriks_satu_langkah, langkah)
    return matriks_peluang_transisi

# Menghitung matriks peluang transisi 2 langkah
matriks_peluang_transisi_2 = hitung_matriks_peluang_transisi(2, matriks_transisi_satu_langkah)

# Menghitung matriks peluang transisi 3 langkah
matriks_peluang_transisi_3 = hitung_matriks_peluang_transisi(3, matriks_transisi_satu_langkah)

# Menghitung matriks peluang transisi 4 langkah
matriks_peluang_transisi_4 = hitung_matriks_peluang_transisi(4, matriks_transisi_satu_langkah)

# Menampilkan hasil perkalian matriks peluang transisi
print("Matriks Peluang Transisi 2 langkah:")
print(matriks_peluang_transisi_2)
print()

print("Matriks Peluang Transisi 3 langkah:")
print(matriks_peluang_transisi_3)
print()

print("Matriks Peluang Transisi 4 langkah:")
print(matriks_peluang_transisi_4)

Matriks Peluang Transisi 2 langkah:
[[0.42737594 0.4548722  0.11775186]
 [0.42253856 0.45547437 0.12198707]
 [0.43912644 0.44125904 0.11961451]]

Matriks Peluang Transisi 3 langkah:
[[0.42678398 0.45321011 0.12000591]
 [0.42671077 0.45360496 0.11968428]
 [0.42545105 0.45424393 0.12030503]]

Matriks Peluang Transisi 4 langkah:
[[0.42655919 0.45354314 0.11989767]
 [0.42660605 0.45348584 0.11990811]
 [0.42664693 0.45350958 0.11984348]]


In [35]:
# Peluang State Indeks BBCA
# Jumlah harian indeks harga saham dalam keadaan turun, naik, dan tetap
jumlah_turun = frekuensi_peralihan_BBCA[0]
jumlah_naik = frekuensi_peralihan_BBCA[1]
jumlah_tetap = frekuensi_peralihan_BBCA[2]

# Jumlah total harian pembukaan harga saham selama enam bulan
jumlah_harian = np.sum(frekuensi_peralihan_BBCA)

# Menghitung peluang state pada awal proses
p_turun = jumlah_turun / jumlah_harian
p_naik = jumlah_naik / jumlah_harian
p_tetap = jumlah_tetap / jumlah_harian

matriks_state_indeks_BBCA = np.array([[p_turun, p_naik, p_tetap]])
# Menampilkan hasil peluang state pada awal proses
print("Peluang state indeks harga saham BBCA pada awal proses:")
print("matriks_state_indeks = [p_turun({}), p_naik({}), p_tetap({})]".format(p_turun, p_naik, p_tetap))

Peluang state indeks harga saham BBCA pada awal proses:
matriks_state_indeks = [p_turun(0.42735042735042733), p_naik(0.4700854700854701), p_tetap(0.10256410256410256)]


In [40]:
# Peluang State Indeks EXCL
# Jumlah harian indeks harga saham dalam keadaan turun, naik, dan tetap
jumlah_turun = frekuensi_peralihan_EXCL[0]
jumlah_naik = frekuensi_peralihan_EXCL[1]
jumlah_tetap = frekuensi_peralihan_EXCL[2]

# Jumlah total harian pembukaan harga saham selama enam bulan
jumlah_harian = np.sum(frekuensi_peralihan_EXCL)

# Menghitung peluang state pada awal proses
p_turun = jumlah_turun / jumlah_harian
p_naik = jumlah_naik / jumlah_harian
p_tetap = jumlah_tetap / jumlah_harian

matriks_state_indeks_EXCL = np.array([[p_turun, p_naik, p_tetap]])
# Menampilkan hasil peluang state pada awal proses
print("Peluang state indeks harga saham EXCL pada awal proses:")
print("matriks_state_indeks = [p_turun({}), p_naik({}), p_tetap({})]".format(p_turun, p_naik, p_tetap))

Peluang state indeks harga saham EXCL pada awal proses:
matriks_state_indeks = [p_turun(0.5128205128205128), p_naik(0.41025641025641024), p_tetap(0.07692307692307693)]


In [43]:
# Peluang State Indeks BBNI
# Jumlah harian indeks harga saham dalam keadaan turun, naik, dan tetap
jumlah_turun = frekuensi_peralihan_BBNI[0]
jumlah_naik = frekuensi_peralihan_BBNI[1]
jumlah_tetap = frekuensi_peralihan_BBNI[2]

# Jumlah total harian pembukaan harga saham selama enam bulan
jumlah_harian = np.sum(frekuensi_peralihan_BBNI)

# Menghitung peluang state pada awal proses
p_turun = jumlah_turun / jumlah_harian
p_naik = jumlah_naik / jumlah_harian
p_tetap = jumlah_tetap / jumlah_harian

matriks_state_indeks_BBNI = np.array([[p_turun, p_naik, p_tetap]])
# Menampilkan hasil peluang state pada awal proses
print("Peluang state indeks harga saham BBNI pada awal proses:")
print("matriks_state_indeks = [p_turun({}), p_naik({}), p_tetap({})]".format(p_turun, p_naik, p_tetap))

Peluang state indeks harga saham BBNI pada awal proses:
matriks_state_indeks = [p_turun(0.48717948717948717), p_naik(0.42735042735042733), p_tetap(0.08547008547008547)]


In [44]:
# Peluang State Indeks BBRI
# Jumlah harian indeks harga saham dalam keadaan turun, naik, dan tetap
jumlah_turun = frekuensi_peralihan_BBRI[0]
jumlah_naik = frekuensi_peralihan_BBRI[1]
jumlah_tetap = frekuensi_peralihan_BBRI[2]

# Jumlah total harian pembukaan harga saham selama enam bulan
jumlah_harian = np.sum(frekuensi_peralihan_BBRI)

# Menghitung peluang state pada awal proses
p_turun = jumlah_turun / jumlah_harian
p_naik = jumlah_naik / jumlah_harian
p_tetap = jumlah_tetap / jumlah_harian

matriks_state_indeks_BBRI = np.array([[p_turun, p_naik, p_tetap]])
# Menampilkan hasil peluang state pada awal proses
print("Peluang state indeks harga saham BBRI pada awal proses:")
print("matriks_state_indeks = [p_turun({}), p_naik({}), p_tetap({})]".format(p_turun, p_naik, p_tetap))

Peluang state indeks harga saham BBRI pada awal proses:
matriks_state_indeks = [p_turun(0.41025641025641024), p_naik(0.5128205128205128), p_tetap(0.07692307692307693)]


In [45]:
# Peluang State Indeks BMRI
# Jumlah harian indeks harga saham dalam keadaan turun, naik, dan tetap
jumlah_turun = frekuensi_peralihan_BMRI[0]
jumlah_naik = frekuensi_peralihan_BMRI[1]
jumlah_tetap = frekuensi_peralihan_BMRI[2]

# Jumlah total harian pembukaan harga saham selama enam bulan
jumlah_harian = np.sum(frekuensi_peralihan_BMRI)

# Menghitung peluang state pada awal proses
p_turun = jumlah_turun / jumlah_harian
p_naik = jumlah_naik / jumlah_harian
p_tetap = jumlah_tetap / jumlah_harian

matriks_state_indeks_BMRI = np.array([[p_turun, p_naik, p_tetap]])
# Menampilkan hasil peluang state pada awal proses
print("Peluang state indeks harga saham BMRI pada awal proses:")
print("matriks_state_indeks = [p_turun({}), p_naik({}), p_tetap({})]".format(p_turun, p_naik, p_tetap))

Peluang state indeks harga saham BMRI pada awal proses:
matriks_state_indeks = [p_turun(0.46153846153846156), p_naik(0.48717948717948717), p_tetap(0.05128205128205128)]


In [46]:
# Peluang State Indeks ASII
# Jumlah harian indeks harga saham dalam keadaan turun, naik, dan tetap
jumlah_turun = frekuensi_peralihan_ASII[0]
jumlah_naik = frekuensi_peralihan_ASII[1]
jumlah_tetap = frekuensi_peralihan_ASII[2]

# Jumlah total harian pembukaan harga saham selama enam bulan
jumlah_harian = np.sum(frekuensi_peralihan_ASII)

# Menghitung peluang state pada awal proses
p_turun = jumlah_turun / jumlah_harian
p_naik = jumlah_naik / jumlah_harian
p_tetap = jumlah_tetap / jumlah_harian

matriks_state_indeks_ASII = np.array([[p_turun, p_naik, p_tetap]])
# Menampilkan hasil peluang state pada awal proses
print("Peluang state indeks harga saham ASII pada awal proses:")
print("matriks_state_indeks = [p_turun({}), p_naik({}), p_tetap({})]".format(p_turun, p_naik, p_tetap))

Peluang state indeks harga saham ASII pada awal proses:
matriks_state_indeks = [p_turun(0.42735042735042733), p_naik(0.4017094017094017), p_tetap(0.17094017094017094)]


In [47]:
# Peluang State Indeks UNVR
# Jumlah harian indeks harga saham dalam keadaan turun, naik, dan tetap
jumlah_turun = frekuensi_peralihan_UNVR[0]
jumlah_naik = frekuensi_peralihan_UNVR[1]
jumlah_tetap = frekuensi_peralihan_UNVR[2]

# Jumlah total harian pembukaan harga saham selama enam bulan
jumlah_harian = np.sum(frekuensi_peralihan_UNVR)

# Menghitung peluang state pada awal proses
p_turun = jumlah_turun / jumlah_harian
p_naik = jumlah_naik / jumlah_harian
p_tetap = jumlah_tetap / jumlah_harian

matriks_state_indeks_UNVR = np.array([[p_turun, p_naik, p_tetap]])
# Menampilkan hasil peluang state pada awal proses
print("Peluang state indeks harga saham UNVR pada awal proses:")
print("matriks_state_indeks = [p_turun({}), p_naik({}), p_tetap({})]".format(p_turun, p_naik, p_tetap))

Peluang state indeks harga saham UNVR pada awal proses:
matriks_state_indeks = [p_turun(0.4700854700854701), p_naik(0.41025641025641024), p_tetap(0.11965811965811966)]


In [48]:
# Peluang State Indeks GGRM
# Jumlah harian indeks harga saham dalam keadaan turun, naik, dan tetap
jumlah_turun = frekuensi_peralihan_GGRM[0]
jumlah_naik = frekuensi_peralihan_GGRM[1]
jumlah_tetap = frekuensi_peralihan_GGRM[2]

# Jumlah total harian pembukaan harga saham selama enam bulan
jumlah_harian = np.sum(frekuensi_peralihan_GGRM)

# Menghitung peluang state pada awal proses
p_turun = jumlah_turun / jumlah_harian
p_naik = jumlah_naik / jumlah_harian
p_tetap = jumlah_tetap / jumlah_harian

matriks_state_indeks_GGRM = np.array([[p_turun, p_naik, p_tetap]])
# Menampilkan hasil peluang state pada awal proses
print("Peluang state indeks harga saham GGRM pada awal proses:")
print("matriks_state_indeks = [p_turun({}), p_naik({}), p_tetap({})]".format(p_turun, p_naik, p_tetap))

Peluang state indeks harga saham GGRM pada awal proses:
matriks_state_indeks = [p_turun(0.5042735042735043), p_naik(0.48717948717948717), p_tetap(0.008547008547008548)]


In [49]:
# Peluang State Indeks INDF
# Jumlah harian indeks harga saham dalam keadaan turun, naik, dan tetap
jumlah_turun = frekuensi_peralihan_INDF[0]
jumlah_naik = frekuensi_peralihan_INDF[1]
jumlah_tetap = frekuensi_peralihan_INDF[2]

# Jumlah total harian pembukaan harga saham selama enam bulan
jumlah_harian = np.sum(frekuensi_peralihan_INDF)

# Menghitung peluang state pada awal proses
p_turun = jumlah_turun / jumlah_harian
p_naik = jumlah_naik / jumlah_harian
p_tetap = jumlah_tetap / jumlah_harian

matriks_state_indeks_INDF = np.array([[p_turun, p_naik, p_tetap]])
# Menampilkan hasil peluang state pada awal proses
print("Peluang state indeks harga saham INDF pada awal proses:")
print("matriks_state_indeks = [p_turun({}), p_naik({}), p_tetap({})]".format(p_turun, p_naik, p_tetap))

Peluang state indeks harga saham INDF pada awal proses:
matriks_state_indeks = [p_turun(0.4017094017094017), p_naik(0.4358974358974359), p_tetap(0.1623931623931624)]


In [50]:
# Peluang State Indeks TLKM
# Jumlah harian indeks harga saham dalam keadaan turun, naik, dan tetap
jumlah_turun = frekuensi_peralihan_TLKM[0]
jumlah_naik = frekuensi_peralihan_TLKM[1]
jumlah_tetap = frekuensi_peralihan_TLKM[2]

# Jumlah total harian pembukaan harga saham selama enam bulan
jumlah_harian = np.sum(frekuensi_peralihan_TLKM)

# Menghitung peluang state pada awal proses
p_turun = jumlah_turun / jumlah_harian
p_naik = jumlah_naik / jumlah_harian
p_tetap = jumlah_tetap / jumlah_harian

matriks_state_indeks_TLKM = np.array([[p_turun, p_naik, p_tetap]])
# Menampilkan hasil peluang state pada awal proses
print("Peluang state indeks harga saham TLKM pada awal proses:")
print("matriks_state_indeks = [p_turun({}), p_naik({}), p_tetap({})]".format(p_turun, p_naik, p_tetap))

Peluang state indeks harga saham TLKM pada awal proses:
matriks_state_indeks = [p_turun(0.4188034188034188), p_naik(0.46153846153846156), p_tetap(0.11965811965811966)]


In [42]:
# Peluang State Indeks BBCA i=8
P_state_1_BBCA = np.dot(matriks_state_indeks_BBCA, matriks_transisi_BBCA)
P_state_2_BBCA = np.dot(P_state_1_BBCA, matriks_transisi_BBCA)
P_state_3_BBCA = np.dot(P_state_2_BBCA, matriks_transisi_BBCA)
P_state_4_BBCA = np.dot(P_state_3_BBCA, matriks_transisi_BBCA)
P_state_5_BBCA = np.dot(P_state_4_BBCA, matriks_transisi_BBCA)
P_state_6_BBCA = np.dot(P_state_5_BBCA, matriks_transisi_BBCA)
P_state_7_BBCA = np.dot(P_state_6_BBCA, matriks_transisi_BBCA)
P_state_8_BBCA = np.dot(P_state_7_BBCA, matriks_transisi_BBCA)

print("P_state_1_BBCA = ", P_state_1_BBCA)
print("P_state_2_BBCA = ", P_state_2_BBCA)
print("P_state_3_BBCA = ", P_state_3_BBCA)
print("P_state_4_BBCA = ", P_state_4_BBCA)
print("P_state_5_BBCA = ", P_state_5_BBCA)
print("P_state_6_BBCA = ", P_state_6_BBCA)
print("P_state_7_BBCA = ", P_state_7_BBCA)
print("P_state_8_BBCA = ", P_state_8_BBCA)

P_state_1_BBCA =  [[0.42735043 0.47008547 0.1025641 ]]
P_state_2_BBCA =  [[0.42735043 0.47008547 0.1025641 ]]
P_state_3_BBCA =  [[0.42735043 0.47008547 0.1025641 ]]
P_state_4_BBCA =  [[0.42735043 0.47008547 0.1025641 ]]
P_state_5_BBCA =  [[0.42735043 0.47008547 0.1025641 ]]
P_state_6_BBCA =  [[0.42735043 0.47008547 0.1025641 ]]
P_state_7_BBCA =  [[0.42735043 0.47008547 0.1025641 ]]
P_state_8_BBCA =  [[0.42735043 0.47008547 0.1025641 ]]


In [52]:
# Peluang State Indeks EXCL i=8
P_state_1_EXCL = np.dot(matriks_state_indeks_EXCL, matriks_transisi_EXCL)
P_state_2_EXCL = np.dot(P_state_1_EXCL, matriks_transisi_EXCL)
P_state_3_EXCL = np.dot(P_state_2_EXCL, matriks_transisi_EXCL)
P_state_4_EXCL = np.dot(P_state_3_EXCL, matriks_transisi_EXCL)
P_state_5_EXCL = np.dot(P_state_4_EXCL, matriks_transisi_EXCL)
P_state_6_EXCL = np.dot(P_state_5_EXCL, matriks_transisi_EXCL)
P_state_7_EXCL = np.dot(P_state_6_EXCL, matriks_transisi_EXCL)
P_state_8_EXCL = np.dot(P_state_7_EXCL, matriks_transisi_EXCL)

print("P_state_1_EXCL = ", P_state_1_EXCL)
print("P_state_2_EXCL = ", P_state_2_EXCL)
print("P_state_3_EXCL = ", P_state_3_EXCL)
print("P_state_4_EXCL = ", P_state_4_EXCL)
print("P_state_5_EXCL = ", P_state_5_EXCL)
print("P_state_6_EXCL = ", P_state_6_EXCL)
print("P_state_7_EXCL = ", P_state_7_EXCL)
print("P_state_8_EXCL = ", P_state_8_EXCL)

P_state_1_EXCL =  [[0.51282051 0.41025641 0.07692308]]
P_state_2_EXCL =  [[0.51282051 0.41025641 0.07692308]]
P_state_3_EXCL =  [[0.51282051 0.41025641 0.07692308]]
P_state_4_EXCL =  [[0.51282051 0.41025641 0.07692308]]
P_state_5_EXCL =  [[0.51282051 0.41025641 0.07692308]]
P_state_6_EXCL =  [[0.51282051 0.41025641 0.07692308]]
P_state_7_EXCL =  [[0.51282051 0.41025641 0.07692308]]
P_state_8_EXCL =  [[0.51282051 0.41025641 0.07692308]]


In [53]:
# Peluang State Indeks BBNI i=8
P_state_1_BBNI = np.dot(matriks_state_indeks_BBNI, matriks_transisi_BBNI)
P_state_2_BBNI = np.dot(P_state_1_BBNI, matriks_transisi_BBNI)
P_state_3_BBNI = np.dot(P_state_2_BBNI, matriks_transisi_BBNI)
P_state_4_BBNI = np.dot(P_state_3_BBNI, matriks_transisi_BBNI)
P_state_5_BBNI = np.dot(P_state_4_BBNI, matriks_transisi_BBNI)
P_state_6_BBNI = np.dot(P_state_5_BBNI, matriks_transisi_BBNI)
P_state_7_BBNI = np.dot(P_state_6_BBNI, matriks_transisi_BBNI)
P_state_8_BBNI = np.dot(P_state_7_BBNI, matriks_transisi_BBNI)

print("P_state_1_BBNI = ", P_state_1_BBNI)
print("P_state_2_BBNI = ", P_state_2_BBNI)
print("P_state_3_BBNI = ", P_state_3_BBNI)
print("P_state_4_BBNI = ", P_state_4_BBNI)
print("P_state_5_BBNI = ", P_state_5_BBNI)
print("P_state_6_BBNI = ", P_state_6_BBNI)
print("P_state_7_BBNI = ", P_state_7_BBNI)
print("P_state_8_BBNI = ", P_state_8_BBNI)

P_state_1_BBNI =  [[0.48717949 0.42735043 0.08547009]]
P_state_2_BBNI =  [[0.48717949 0.42735043 0.08547009]]
P_state_3_BBNI =  [[0.48717949 0.42735043 0.08547009]]
P_state_4_BBNI =  [[0.48717949 0.42735043 0.08547009]]
P_state_5_BBNI =  [[0.48717949 0.42735043 0.08547009]]
P_state_6_BBNI =  [[0.48717949 0.42735043 0.08547009]]
P_state_7_BBNI =  [[0.48717949 0.42735043 0.08547009]]
P_state_8_BBNI =  [[0.48717949 0.42735043 0.08547009]]


In [54]:
# Peluang State Indeks BBRI i=8
P_state_1_BBRI = np.dot(matriks_state_indeks_BBRI, matriks_transisi_BBRI)
P_state_2_BBRI = np.dot(P_state_1_BBRI, matriks_transisi_BBRI)
P_state_3_BBRI = np.dot(P_state_2_BBRI, matriks_transisi_BBRI)
P_state_4_BBRI = np.dot(P_state_3_BBRI, matriks_transisi_BBRI)
P_state_5_BBRI = np.dot(P_state_4_BBRI, matriks_transisi_BBRI)
P_state_6_BBRI = np.dot(P_state_5_BBRI, matriks_transisi_BBRI)
P_state_7_BBRI = np.dot(P_state_6_BBRI, matriks_transisi_BBRI)
P_state_8_BBRI = np.dot(P_state_7_BBRI, matriks_transisi_BBRI)

print("P_state_1_BBRI = ", P_state_1_BBRI)
print("P_state_2_BBRI = ", P_state_2_BBRI)
print("P_state_3_BBRI = ", P_state_3_BBRI)
print("P_state_4_BBRI = ", P_state_4_BBRI)
print("P_state_5_BBRI = ", P_state_5_BBRI)
print("P_state_6_BBRI = ", P_state_6_BBRI)
print("P_state_7_BBRI = ", P_state_7_BBRI)
print("P_state_8_BBRI = ", P_state_8_BBRI)

P_state_1_BBRI =  [[0.4017094  0.52136752 0.07692308]]
P_state_2_BBRI =  [[0.40188746 0.52065527 0.07745726]]
P_state_3_BBRI =  [[0.40183924 0.52058108 0.07757968]]
P_state_4_BBRI =  [[0.40183004 0.52055666 0.0776133 ]]
P_state_5_BBRI =  [[0.40182743 0.52055029 0.07762228]]
P_state_6_BBRI =  [[0.40182674 0.52054857 0.07762469]]
P_state_7_BBRI =  [[0.40182655 0.52054811 0.07762533]]
P_state_8_BBRI =  [[0.4018265  0.52054799 0.07762551]]


In [55]:
# Peluang State Indeks BMRI i=8
P_state_1_BMRI = np.dot(matriks_state_indeks_BMRI, matriks_transisi_BMRI)
P_state_2_BMRI = np.dot(P_state_1_BMRI, matriks_transisi_BMRI)
P_state_3_BMRI = np.dot(P_state_2_BMRI, matriks_transisi_BMRI)
P_state_4_BMRI = np.dot(P_state_3_BMRI, matriks_transisi_BMRI)
P_state_5_BMRI = np.dot(P_state_4_BMRI, matriks_transisi_BMRI)
P_state_6_BMRI = np.dot(P_state_5_BMRI, matriks_transisi_BMRI)
P_state_7_BMRI = np.dot(P_state_6_BMRI, matriks_transisi_BMRI)
P_state_8_BMRI = np.dot(P_state_7_BMRI, matriks_transisi_BMRI)

print("P_state_1_BMRI = ", P_state_1_BMRI)
print("P_state_2_BMRI = ", P_state_2_BMRI)
print("P_state_3_BMRI = ", P_state_3_BMRI)
print("P_state_4_BMRI = ", P_state_4_BMRI)
print("P_state_5_BMRI = ", P_state_5_BMRI)
print("P_state_6_BMRI = ", P_state_6_BMRI)
print("P_state_7_BMRI = ", P_state_7_BMRI)
print("P_state_8_BMRI = ", P_state_8_BMRI)

P_state_1_BMRI =  [[0.47008547 0.47863248 0.05128205]]
P_state_2_BMRI =  [[0.4687526  0.47994035 0.05130704]]
P_state_3_BMRI =  [[0.46896813 0.47973004 0.05130183]]
P_state_4_BMRI =  [[0.46893292 0.47976435 0.05130273]]
P_state_5_BMRI =  [[0.46893869 0.47975873 0.05130258]]
P_state_6_BMRI =  [[0.46893774 0.47975965 0.05130261]]
P_state_7_BMRI =  [[0.4689379 0.4797595 0.0513026]]
P_state_8_BMRI =  [[0.46893787 0.47975952 0.05130261]]


In [ ]:
# Peluang State Indeks BBNI i=8
P_state_1_BBNI = np.dot(matriks_state_indeks_BBNI, matriks_transisi_BBNI)
P_state_2_BBNI = np.dot(P_state_1_BBNI, matriks_transisi_BBNI)
P_state_3_BBNI = np.dot(P_state_2_BBNI, matriks_transisi_BBNI)
P_state_4_BBNI = np.dot(P_state_3_BBNI, matriks_transisi_BBNI)
P_state_5_BBNI = np.dot(P_state_4_BBNI, matriks_transisi_BBNI)
P_state_6_BBNI = np.dot(P_state_5_BBNI, matriks_transisi_BBNI)
P_state_7_BBNI = np.dot(P_state_6_BBNI, matriks_transisi_BBNI)
P_state_8_BBNI = np.dot(P_state_7_BBNI, matriks_transisi_BBNI)

print("P_state_1_BBNI = ", P_state_1_BBNI)
print("P_state_2_BBNI = ", P_state_2_BBNI)
print("P_state_3_BBNI = ", P_state_3_BBNI)
print("P_state_4_BBNI = ", P_state_4_BBNI)
print("P_state_5_BBNI = ", P_state_5_BBNI)
print("P_state_6_BBNI = ", P_state_6_BBNI)
print("P_state_7_BBNI = ", P_state_7_BBNI)
print("P_state_8_BBNI = ", P_state_8_BBNI)

In [ ]:
# Peluang State Indeks BBNI i=8
P_state_1_BBNI = np.dot(matriks_state_indeks_BBNI, matriks_transisi_BBNI)
P_state_2_BBNI = np.dot(P_state_1_BBNI, matriks_transisi_BBNI)
P_state_3_BBNI = np.dot(P_state_2_BBNI, matriks_transisi_BBNI)
P_state_4_BBNI = np.dot(P_state_3_BBNI, matriks_transisi_BBNI)
P_state_5_BBNI = np.dot(P_state_4_BBNI, matriks_transisi_BBNI)
P_state_6_BBNI = np.dot(P_state_5_BBNI, matriks_transisi_BBNI)
P_state_7_BBNI = np.dot(P_state_6_BBNI, matriks_transisi_BBNI)
P_state_8_BBNI = np.dot(P_state_7_BBNI, matriks_transisi_BBNI)

print("P_state_1_BBNI = ", P_state_1_BBNI)
print("P_state_2_BBNI = ", P_state_2_BBNI)
print("P_state_3_BBNI = ", P_state_3_BBNI)
print("P_state_4_BBNI = ", P_state_4_BBNI)
print("P_state_5_BBNI = ", P_state_5_BBNI)
print("P_state_6_BBNI = ", P_state_6_BBNI)
print("P_state_7_BBNI = ", P_state_7_BBNI)
print("P_state_8_BBNI = ", P_state_8_BBNI)

In [ ]:
# Peluang State Indeks BBNI i=8
P_state_1_BBNI = np.dot(matriks_state_indeks_BBNI, matriks_transisi_BBNI)
P_state_2_BBNI = np.dot(P_state_1_BBNI, matriks_transisi_BBNI)
P_state_3_BBNI = np.dot(P_state_2_BBNI, matriks_transisi_BBNI)
P_state_4_BBNI = np.dot(P_state_3_BBNI, matriks_transisi_BBNI)
P_state_5_BBNI = np.dot(P_state_4_BBNI, matriks_transisi_BBNI)
P_state_6_BBNI = np.dot(P_state_5_BBNI, matriks_transisi_BBNI)
P_state_7_BBNI = np.dot(P_state_6_BBNI, matriks_transisi_BBNI)
P_state_8_BBNI = np.dot(P_state_7_BBNI, matriks_transisi_BBNI)

print("P_state_1_BBNI = ", P_state_1_BBNI)
print("P_state_2_BBNI = ", P_state_2_BBNI)
print("P_state_3_BBNI = ", P_state_3_BBNI)
print("P_state_4_BBNI = ", P_state_4_BBNI)
print("P_state_5_BBNI = ", P_state_5_BBNI)
print("P_state_6_BBNI = ", P_state_6_BBNI)
print("P_state_7_BBNI = ", P_state_7_BBNI)
print("P_state_8_BBNI = ", P_state_8_BBNI)

In [ ]:
# Peluang State Indeks BBNI i=8
P_state_1_BBNI = np.dot(matriks_state_indeks_BBNI, matriks_transisi_BBNI)
P_state_2_BBNI = np.dot(P_state_1_BBNI, matriks_transisi_BBNI)
P_state_3_BBNI = np.dot(P_state_2_BBNI, matriks_transisi_BBNI)
P_state_4_BBNI = np.dot(P_state_3_BBNI, matriks_transisi_BBNI)
P_state_5_BBNI = np.dot(P_state_4_BBNI, matriks_transisi_BBNI)
P_state_6_BBNI = np.dot(P_state_5_BBNI, matriks_transisi_BBNI)
P_state_7_BBNI = np.dot(P_state_6_BBNI, matriks_transisi_BBNI)
P_state_8_BBNI = np.dot(P_state_7_BBNI, matriks_transisi_BBNI)

print("P_state_1_BBNI = ", P_state_1_BBNI)
print("P_state_2_BBNI = ", P_state_2_BBNI)
print("P_state_3_BBNI = ", P_state_3_BBNI)
print("P_state_4_BBNI = ", P_state_4_BBNI)
print("P_state_5_BBNI = ", P_state_5_BBNI)
print("P_state_6_BBNI = ", P_state_6_BBNI)
print("P_state_7_BBNI = ", P_state_7_BBNI)
print("P_state_8_BBNI = ", P_state_8_BBNI)

In [ ]:
# Peluang State Indeks BBNI i=8
P_state_1_BBNI = np.dot(matriks_state_indeks_BBNI, matriks_transisi_BBNI)
P_state_2_BBNI = np.dot(P_state_1_BBNI, matriks_transisi_BBNI)
P_state_3_BBNI = np.dot(P_state_2_BBNI, matriks_transisi_BBNI)
P_state_4_BBNI = np.dot(P_state_3_BBNI, matriks_transisi_BBNI)
P_state_5_BBNI = np.dot(P_state_4_BBNI, matriks_transisi_BBNI)
P_state_6_BBNI = np.dot(P_state_5_BBNI, matriks_transisi_BBNI)
P_state_7_BBNI = np.dot(P_state_6_BBNI, matriks_transisi_BBNI)
P_state_8_BBNI = np.dot(P_state_7_BBNI, matriks_transisi_BBNI)

print("P_state_1_BBNI = ", P_state_1_BBNI)
print("P_state_2_BBNI = ", P_state_2_BBNI)
print("P_state_3_BBNI = ", P_state_3_BBNI)
print("P_state_4_BBNI = ", P_state_4_BBNI)
print("P_state_5_BBNI = ", P_state_5_BBNI)
print("P_state_6_BBNI = ", P_state_6_BBNI)
print("P_state_7_BBNI = ", P_state_7_BBNI)
print("P_state_8_BBNI = ", P_state_8_BBNI)